# Generated by Django 4.0 on 2023-12-01 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_example', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examplemodel',
            old_name='image_field',
            new_name='file_upload',
        ),
        migrations.RemoveField(
            model_name='examplemodel',
            name='file_field',
        ),
    ]
